name: Main
on:
  workflow_dispatch: {}
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: verify

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Build and Verify
        uses: ./.github/actions/verify
