name: Publish
on:
  release:
    types: [published]
  
concurrency:
  group: publish

permissions:
  # IMPORTANT: this permission is mandatory for trusted publishing
  id-token: write

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Build and Verify
        uses: ./.github/actions/verify

      - name: Package
        run: poetry build

      - name: Publish
        uses: pypa/gh-action-pypi-publish@release/v1
